use_frameworks!

target 'MRTableViewCellCountScrollIndicator_Example' do
  pod 'MRTableViewCellCountScrollIndicator', :path => '../'
  pod 'RestKit', '~> 0.27.0'
  
  target 'MRTableViewCellCountScrollIndicator_Tests' do
    inherit! :search_paths

    
  end
end
